# Generated by Django 4.0 on 2022-05-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userr',
        ),
    ]
