# Generated by Django 4.0 on 2022-05-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_like_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_like',
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
