# Generated by Django 4.0 on 2022-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_like_user_like_like_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
