# Generated by Django 4.0.4 on 2022-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_like_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(blank=True, max_length=70)),
                ('proflie_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('post_num', models.IntegerField()),
            ],
        ),
    ]
