# Generated by Django 4.0.4 on 2022-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user_insta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_insta',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_insta',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
