# Generated by Django 4.0.4 on 2022-05-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0014_alter_post_userr'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentPost',
            fields=[
                ('timestamps', models.DateTimeField(auto_created=True)),
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.commentpost')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
